/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  identifier: string;
  items?: Array<
    {
      _key: string;
    } & MenuItem
  >;
};

export type TranslationNamespace = {
  _id: string;
  _type: "translationNamespace";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  slug: Slug;
  keys?: Array<{
    key: string;
    description?: string;
    translations?: InternationalizedArrayString;
    _type: "translationKey";
    _key: string;
  }>;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Locale = {
  _id: string;
  _type: "locale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: InternationalizedArrayString;
  localeId: string;
};

export type WorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "work";
};

export type SelectedWork = {
  _type: "selectedWork";
  items?: Array<
    {
      _key: string;
    } & WorkReference
  >;
};

export type Textblock = {
  _type: "textblock";
  titleBlocks?: Array<string>;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<
    {
      _key: string;
    } & LinkItem
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Hero = {
  _type: "hero";
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform:
    | "linkedin"
    | "instagram"
    | "facebook"
    | "x"
    | "youtube"
    | "tiktok"
    | "github"
    | "other";
  url: string;
  label?: string;
};

export type PrivacyPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "privacyPage";
};

export type LegalLink = {
  _type: "legalLink";
  label: string;
  internal?: PrivacyPageReference;
  external?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type CareersPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "careersPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type ExpertiseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "expertise";
};

export type JobReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "job";
};

export type MenuItem = {
  _type: "menuItem";
  label: InternationalizedArrayString;
  internal?:
    | HomePageReference
    | AboutPageReference
    | CareersPageReference
    | ContactPageReference
    | PrivacyPageReference
    | WorkReference
    | ExpertiseReference
    | JobReference;
  external?: string;
  openInNewTab?: boolean;
};

export type LinkItem = {
  _type: "linkItem";
  label: string;
  url: string;
};

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type InternationalizedArraySlugValue = {
  _type: "internationalizedArraySlugValue";
  value?: Slug;
  language: string;
};

export type InternationalizedArrayBlockContentTextOnlyValue = {
  _type: "internationalizedArrayBlockContentTextOnlyValue";
  value?: BlockContentTextOnly;
  language: string;
};

export type InternationalizedArrayBlockContentValue = {
  _type: "internationalizedArrayBlockContentValue";
  value?: BlockContent;
  language: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language: string;
};

export type InternationalizedArraySlug = Array<
  {
    _key: string;
  } & InternationalizedArraySlugValue
>;

export type InternationalizedArrayBlockContentTextOnly = Array<
  {
    _key: string;
  } & InternationalizedArrayBlockContentTextOnlyValue
>;

export type InternationalizedArrayBlockContent = Array<
  {
    _key: string;
  } & InternationalizedArrayBlockContentValue
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomePageReference
    | AboutPageReference
    | CareersPageReference
    | ContactPageReference
    | PrivacyPageReference
    | SiteSettingsReference
    | WorkReference
    | ExpertiseReference
    | PersonReference
    | JobReference;
  language: string;
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  type?: "full-time" | "part-time" | "internship" | "freelance";
  location?: LocationReference;
  expertise?: ExpertiseReference;
  publishDate?: string;
  recruiteeId?: string;
  introIndex?: string;
  introDetail?: string;
  jobDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profile?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  offer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  spotify?: string;
  contact?: PersonReference;
  showOnHome?: boolean;
  order?: number;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  street?: InternationalizedArrayString;
  number?: string;
  postalCode?: string;
  city?: InternationalizedArrayString;
  country?: InternationalizedArrayString;
  email?: string;
  phone?: string;
};

export type Expertise = {
  _id: string;
  _type: "expertise";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  intro?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lead?: PersonReference;
  links?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  order?: number;
  recruiteeId?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  name: string;
  position?: string;
  intro?: string;
  phone?: string;
  email?: string;
};

export type Work = {
  _id: string;
  _type: "work";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  intro?: string;
  expertises?: Array<
    {
      _key: string;
    } & ExpertiseReference
  >;
  year?: number;
  code?: string;
  gradient?: string;
  brief?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
  approach?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
  context?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
  outcome?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
  related?: Array<
    {
      _key: string;
    } & WorkReference
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title: string;
  tagline?: string;
  email?: string;
  phone?: string;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  legalLinks?: Array<
    {
      _key: string;
    } & LegalLink
  >;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
};

export type CareersPage = {
  _id: string;
  _type: "careersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Textblock)
    | ({
        _key: string;
      } & SelectedWork)
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Menu
  | TranslationNamespace
  | InternationalizedArrayString
  | Slug
  | Locale
  | WorkReference
  | SelectedWork
  | Textblock
  | SanityFileAssetReference
  | SanityImageAssetReference
  | Hero
  | SocialLink
  | PrivacyPageReference
  | LegalLink
  | HomePageReference
  | AboutPageReference
  | CareersPageReference
  | ContactPageReference
  | ExpertiseReference
  | JobReference
  | MenuItem
  | LinkItem
  | BlockContentTextOnly
  | BlockContent
  | InternationalizedArraySlugValue
  | InternationalizedArrayBlockContentTextOnlyValue
  | InternationalizedArrayBlockContentValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArraySlug
  | InternationalizedArrayBlockContentTextOnly
  | InternationalizedArrayBlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayText
  | TranslationMetadata
  | InternationalizedArrayReference
  | SiteSettingsReference
  | PersonReference
  | InternationalizedArrayReferenceValue
  | LocationReference
  | Job
  | Location
  | Expertise
  | Person
  | Work
  | SiteSettings
  | PrivacyPage
  | ContactPage
  | CareersPage
  | AboutPage
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/hooks/useSanityApi.ts
// Variable: SETTINGS_PROJECTION
// Query: {  title,  email,  phone,  socials[]{    platform,    url,    "label": coalesce(label, platform)  },  legalLinks[]{    label,    "href": coalesce(external, select(internal->_type == "privacyPage" => "/privacy"))  }}
export type SETTINGS_PROJECTION_RESULT = {
  title: never;
  email: never;
  phone: never;
  socials: never;
  legalLinks: never;
};

// Source: ../src/hooks/useSanityApi.ts
// Variable: footerContentQuery
// Query: {  "settings": *[_type == "siteSettings" && (locale == $locale || locale == null)] | order(locale desc)[0]{  title,  email,  phone,  socials[]{    platform,    url,    "label": coalesce(label, platform)  },  legalLinks[]{    label,    "href": coalesce(external, select(internal->_type == "privacyPage" => "/privacy"))  }},  "fallbackSettings": *[_type == "siteSettings"][0]{  title,  email,  phone,  socials[]{    platform,    url,    "label": coalesce(label, platform)  },  legalLinks[]{    label,    "href": coalesce(external, select(internal->_type == "privacyPage" => "/privacy"))  }},  "locations": *[_type == "location"] | order(_createdAt asc){    "title": coalesce(title[_key == $locale][0].value, title[_key == "en"][0].value, title[0].value),    "street": coalesce(street[_key == $locale][0].value, street[_key == "en"][0].value, street[0].value),    number,    postalCode,    "city": coalesce(city[_key == $locale][0].value, city[_key == "en"][0].value, city[0].value),    "country": coalesce(country[_key == $locale][0].value, country[_key == "en"][0].value, country[0].value)  }}
export type FooterContentQueryResult = {
  settings: {
    title: string;
    email: string | null;
    phone: string | null;
    socials: Array<{
      platform:
        | "facebook"
        | "github"
        | "instagram"
        | "linkedin"
        | "other"
        | "tiktok"
        | "x"
        | "youtube";
      url: string;
      label:
        | string
        | "facebook"
        | "github"
        | "instagram"
        | "linkedin"
        | "other"
        | "tiktok"
        | "x"
        | "youtube";
    }> | null;
    legalLinks: Array<{
      label: string;
      href: string | "/privacy";
    }> | null;
  } | null;
  fallbackSettings: {
    title: string;
    email: string | null;
    phone: string | null;
    socials: Array<{
      platform:
        | "facebook"
        | "github"
        | "instagram"
        | "linkedin"
        | "other"
        | "tiktok"
        | "x"
        | "youtube";
      url: string;
      label:
        | string
        | "facebook"
        | "github"
        | "instagram"
        | "linkedin"
        | "other"
        | "tiktok"
        | "x"
        | "youtube";
    }> | null;
    legalLinks: Array<{
      label: string;
      href: string | "/privacy";
    }> | null;
  } | null;
  locations: Array<{
    title: string | null;
    street: string | null;
    number: string | null;
    postalCode: string | null;
    city: string | null;
    country: string | null;
  }>;
};

// Source: ../src/hooks/useSanityApi.ts
// Variable: menuByIdentifierQuery
// Query: *[_type == "menu" && identifier == $identifier][0]{  identifier,  items[]{    "label": coalesce(label[_key == $locale][0].value, label[_key == "en"][0].value, label[0].value),    "url": coalesce(      select(        internal->_type == "homePage" => "/",        internal->_type == "aboutPage" => "/about",        internal->_type == "careersPage" => "/careers",        internal->_type == "contactPage" => "/contact",        internal->_type == "privacyPage" => "/privacy",        internal->_type == "work" => "/work/" + internal->slug.current,        internal->_type == "expertise" => "/expertise/" + internal->slug.current,        internal->_type == "job" => "/careers/" + internal->slug.current      ),      external    ),    openInNewTab  }}
export type MenuByIdentifierQueryResult = {
  identifier: string;
  items: Array<{
    label: string | null;
    url: string | "/" | "/about" | "/careers" | "/contact" | "/privacy" | null;
    openInNewTab: boolean | null;
  }> | null;
} | null;
